<?php
/**
 * @file
 * Позволяет пользователям добавлять в ноды персональные аннотации.
 *
 * При выводе ноды добавляет текстовое поле, которое позволяет
 * аутентифицированным пользователям вставлять примечания.
 */

/**
 * Реализация hook_menu().
 */
function annotate_menu() {
    $items['admin/config/annotate'] = array(
        'title' => 'Node annotation',
        'description' => 'Adjust node annotation options.',
        'position' => 'right',
        'weight' => -5,
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('administer site configuration'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );
    $items['admin/config/annotate/settings'] = array(
        'title' => 'Annotation settings',
        'description' => 'Change how annotations behave.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('annotate_admin_settings'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'annotate.admin.inc',
    );
    return $items;
}

/**
 * Реализация hook_node_load()
 */
function annotate_node_load($nodes, $types) {
    global $user;
// Проверка, является ли лицо, просматривающее ноду, автором.
// Если нет, аннотация скрывается.
    foreach ($nodes as $node) {
        if ($user->uid != $node->uid) {
            unset($node->annotation);
        }
    }
}